version: '3.8'

services:
    redis:
        image: 'redislabs/rejson:latest'
        ports:
            - 6379:6379

    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8081:8081
        depends_on:
            - redis

    api:
        build:
            context: .
            dockerfile: src/nest/Dockerfile
            target: development
        volumes:
            - .:/usr/src/digitaltwin/api
        command: yarn dev
        ports:
            - 3000:3000
        depends_on:
            - redis
